### PR TITLE
report issue form working and other contact updates

### PR DESCRIPTION
**Pull request by mshick**
### Test Plan (Steps to test):

1. Go to subscriptions -> orders -> report an issue
1. Type a message and submit it. 
1. Check in gorgias that the message looks as you'd expect.
2. Go to `/contact`. Notice your session info pre-populates if you're signed in.
3. Send a message. 
4. Check that it looks okay in Gorgias.

### CODE REVIEW

**Review by mcat — COMMENTED** [review]
Report and Issue looks good! One thing I noticed is that in Gorgias you get an error that says the user doesn't exist. Not sure if this matters. But looked like it could be an issue. 

Screen Shot 2022-09-01 at 15 27 59

Contact page prefilling works great! However, it looks like the phone number isn't being prefilled

**Comment by mshick** [comment]
@mcat Phone # is optional and not available easily. I'm just populating required fields to remove an annoyance for the customer.

**Comment by mshick** [comment]
@mcat  I just confirmed with Gorgias — the error you're seeing is because you're also a user. It's a benign error, and kind of dumb. Doesn't happen if you use a non-user email.

**Review by mcat — APPROVED** [review]
👍

**Pull request merged**
