### PR TITLE
Recharge

### PR DESCRIPTION
**Pull request by robgrant**
### Test Plan (Steps to test):

1. Sign in on the preview site.
2. Go through checkout and create two new subscriptions. You can create subs for mesh shorts or exceptional t-shirt.
3. Go to Account > Subs
4. Try out all the buttons and action links. 
5. Cancel one of your subs, and review the display of a canceled sub.

### Checklist:

- [x] Create a Test Plan
- [x] Changes Communicated (in commits or above)
- [x] Docs Updated
- [x] Storybook Updated

### CODE REVIEW

**Comment by mshick** [comment]
1. This subscription is yours, not mine, appearing in my list:

Screenshot 2022-09-02 at 14 42 29

Screenshot 2022-09-02 at 14 43 14

2. Update product options from overview triggers an error:

From: Mesh Gym Shorts, Black, Small, Quantity 1
To: Mesh Gym Shorts, White, Medium, Quantity 2

Screenshot 2022-09-02 at 14 12 08

3. Unhandled shipping status style:

Screenshot 2022-09-02 at 14 38 56

4. Update next charge date not mutating subscription data. 9/28 -> 9/29 but still seeing 9/28 on the Manage screen. After a full refresh the Manage screen updates.

5. Delivery frequency current value not selected. 

6. Updating delivery frequency does not update the parent subscription.

7. Updating address leads to `TypeError: Cannot read properties of undefined (reading 'payment_details')`. Subs are now borked, so I can't test further.

**Comment by mshick** [comment]
Report Issue button not showing for past orders. All orders past the status where they can be skipped should show this button.

Screenshot 2022-09-02 at 15 59 50

Also, oddly, images aren't loading for orders? They are for a different subscription, so something else might be amiss here.

**Comment by mshick** [comment]
Order Now text, current text below:

Screenshot 2022-09-02 at 16 03 16

Instead it should reflect the current one-time nature:

Screen 1:

```
Order the same product to be processed immediately using this subscription's payment method.

This will not affect your upcoming delivery on DATE and it will not receive your standard subscription discounts.
```

Screen 2:

```
Your one-time order is being processed.
```

Also, I'm not seeing any indication the one-time orders are processing. Can you verify they are making their way into Recharge?

**Comment by mshick** [comment]
Loading and reloading behavior needs work. The loading screen looks like this:

Screenshot 2022-09-02 at 14 38 14

I think a better look would be to use a skeleton, similar to purchases, and end with the No Active Subscriptions screen if nothing loads.

Also, the re-fetch behavior should be improved. Every time a switch away from the tab it reloads. This might be a separate story though. I'll file one.

**Comment by mshick** [comment]
I'm now seeing changes to the parent subscription data reflected, however the delay after the modal closes is odd. Can we somehow tie the `isSubmitSuccessful` event to the subscription object update being executed? Maybe there's another approach?

**Comment by mshick** [comment]
Odd behaviors with skipping orders. For instance, I skipped a Sept 12 order, with no other displayed, and suddenly I had a December 11th order then the skipped Sept 12th order. 

The top / upcoming orders shown should remain consistent, their sort should stay the same, and they should only change their status when skipping / unskipping.

Also, top / upcoming orders are an ascending chronological sort that starts with the most recent order in the past and continues into the future. I believe there's a limit to how many future orders Recharge will return — 2 or 3...

Past Orders is all orders that are in the past except the most recent, and it is a reverse chronological sort.

**Comment by mshick** [comment]
Cancel Subscription does not work:

```
{
    "errors": [
        {
            "message": "Status Code: 415 Response Body: {\"error\":\"Bad Request\",\"message\":\"The server has refused to accept the request because the payload format is in an unsupported format\"}\n",
            "locations": [
                {
                    "line": 110,
                    "column": 3
                }
            ],
            "path": [
                "subscription"
            ],
            "type": "GraphQLError"
        }
    ],
    "data": {
        "subscription": null
    }
}
```

We will need some cancelled subs to review the Past Subscriptions features.

**Comment by mshick** [comment]
All amounts are off, which you already know.

The approach I would have take here is to use the transforms to process the data and create a subscription object that consistently has all calculations made — e.g., amount would be calculated once, and `subscription.amount` (e.g.) would be read and displayed in the various components. 

I haven't dug into the code yet, so I'm not sure what your approach was, just a suggestion.

**Comment by mshick** [comment]
Past subscriptions need the loading skeleton treatment:

Screenshot 2022-09-06 at 10 57 17

**Review by mshick — CHANGES_REQUESTED** [review]
A few minor things. Overall looks great.

Overall I think it would be better to conform the objects used in the components to the project styles and abstract our working `subscription` away from the specific Recharge subscription, but that can happen in follow up work.

**Comment by mshick** [comment]
`Update product` no longer does anything. I've changed color / size / quantity and no changes are reflected. Not even after a full refresh.

**Comment by mshick** [comment]
`Update payment method` changes are not reflected on the subscription. They show up after a full refresh.

**Comment by mshick** [comment]
`Skip next order` button appears to act twice. First it skips the next available order, then it gives another message saying it has skipped the order after that — e.g., I skip Dec 12th, and I see two confirmation screens one after the other, saying Skipped Dec 12th, Skipped March 11th. March 11th isn't actually skipped.

**Comment by mshick** [comment]
`Order now` text has placeholder `DATE` in it.

**Comment by mshick** [comment]
`Order now` doesn't seem to do anything. No record of an order in Recharge or in Shopify. Am I looking in the wrong place? Maybe the `onetime` endpoint doesn't work?

**Comment by mshick** [comment]
`Update delivery frequency` does not seem to do anything. I changed from 90 -> 30 days and the change is not reflected. I am able to do this update in the Recharge portal.

Here's the request in the Recharge portal.

POST `/subscriptions/271016815`

```
delivery_option: 30
order_interval_frequency: 30
charge_interval_frequency: 30
order_interval_unit: day
```

**Comment by mshick** [comment]
Changing the address leads to an error like before, when the payment method wasn't associated.

I'm using this build (the most recent on the PR) https://penny-git-sc-9488-featureintegrate-recharge-wi-9dfeb3-takeshape.vercel.app/account/subscriptions. Is this correct? I'm surprised to see all these errors resurface.

**Review by mshick — CHANGES_REQUESTED** [review]
Update product no longer does anything. I've changed color / size / quantity and no changes are reflected. Not even after a full refresh.

**Review by asprouse — APPROVED** [review]
From a user POV everything looks great!

**Review by mshick — APPROVED** [review]

**Pull request merged**
