### PR TITLE
Deps

### PR DESCRIPTION
**Pull request by mshick**
### Test Plan (Steps to test):

1. Does it blend? (build and deploy)
2. If you really want, pull this branch, `npm install` and `npm run dev` to  see if local dev still works.

### CODE REVIEW

**Comment by allanlasser** [comment]
Trying to log in returns a 500 error page 😢

**Comment by allanlasser** [comment]
Signing in with Google when running the dev server returns this error:
```
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error client_id is required {
  error: {
    message: 'client_id is required',
    stack: 'TypeError: client_id is required\n' +
      '    at new BaseClient (/Users/allan/Developer/takeshape/deluxe-sample-project/node_modules/openid-client/lib/client.js:178:13)\n' +
      '    at new Client (/Users/allan/Developer/takeshape/deluxe-sample-project/node_modules/openid-client/lib/client.js:1830:7)\n' +
      '    at openidClient (/Users/allan/Developer/takeshape/deluxe-sample-project/node_modules/next-auth/core/lib/oauth/client.js:28:18)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async getAuthorizationUrl (/Users/allan/Developer/takeshape/deluxe-sample-project/node_modules/next-auth/core/lib/oauth/authorization-url.js:67:18)\n' +
      '    at async Object.signin (/Users/allan/Developer/takeshape/deluxe-sample-project/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
      '    at async NextAuthHandler (/Users/allan/Developer/takeshape/deluxe-sample-project/node_modules/next-auth/core/index.js:253:26)\n' +
      '    at async NextAuthNextHandler (/Users/allan/Developer/takeshape/deluxe-sample-project/node_modules/next-auth/next/index.js:23:19)\n' +
      '    at async /Users/allan/Developer/takeshape/deluxe-sample-project/node_modules/next-auth/next/index.js:59:32',
    name: 'TypeError'
  },
  providerId: 'google',
  message: 'client_id is required'
}
```

**Comment by mshick** [comment]
@allanlasser Working for me. Are you sure you have the ENV vars you need? `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` in your `.env.local`

**Comment by allanlasser** [comment]
> @allanlasser Working for me. Are you sure you have the ENV vars you need? `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` in your `.env.local`

Ah yep that's it, no GOOGLE secrets!

**Review by allanlasser — APPROVED** [review]
Everything is working well, except for two Chromatic storybooks that are still failing.

**Comment by mshick** [comment]
Got 'em!

**Pull request merged**
