### PR TITLE
delivery status components

### PR DESCRIPTION
**Pull request by mshick**
### Screenshots

Screenshot 2022-09-15 at 13 13 16

### Test Plan (Steps to test):

1. Create a subscription, or use an existing
1. Log in to the Shopify admin for DSP. Find one of your subscription orders and manually fulfill it. Give a shipping company name and tracking number.
1. Check on that order in your Penny Accounts > Subscriptions section. You should see the order at the fulfilled status, and be able to click a `Tracking Info` button on the order entry.

### CODE REVIEW

**Comment by allanlasser** [comment]
After logging into my account and checking the `/account/subscriptions` page, the query 404'd and no error was reported:

```{"errors":[{"message":"Status Code: 404 Response Body: {\"errors\":[\"shopify_customer_id not found\"]}\n","locations":[{"line":219,"column":3}],"path":["subscriptions"],"type":"GraphQLError"}],"data":{"subscriptions":null}}```

Screen Shot 2022-09-16 at 2 36 24 PM

**Comment by allanlasser** [comment]
- After fulfilling the order:
    - The "scheduled for" date didn't update to the next shipment date, instead stayed on the current shipment date.
    - It was hard for me to know how to track the order, it took a few clicks before I found it on the orders tab. Having a "tracking info" link below the "Order fulfilled" status line would be pretty handy.
    Screen Shot 2022-09-16 at 2 44 24 PM


- When clicking "Tracking Info," I expected to be taken to the shipper's tracking page, not to have a modal open. I don't think we need this modal:
    - The "Report Issue" link the modal is also present on the order list item.
    - The shipper's webpage would have information like shipping address and more granular shipping status.

- The modal that popped up after clicking "Tracking Info" has awkward overflow scrolling:

https://user-images.githubusercontent.com/6089482/190709572-727d9eac-0d93-422d-80ed-7f1c0fe1cc0b.mov

**Review by allanlasser — CHANGES_REQUESTED** [review]
No code feedback, just testing feedback above.

**Comment by mshick** [comment]
@allanlasser That's odd about the error. I've filed a story here: https://app.shortcut.com/takeshape/story/9840/issue-with-account-subscriptions-when-the-user-has-no-subscriptions

**Comment by mshick** [comment]
@allanlasser We're not guaranteed a shipper URL, and the modal handles states that wouldn't necessarily be handled by the shipper. Likewise, I think it's important to give the user information to look up the shipment on their own, like shipping company and tracking #, or to report issues. These order records are historic, while the tracking URLs are not necessarily, e.g., shipping address was incorrect leading to a failed delivery and to "debug" the situation with the carrier the customer needs to convey info on the phone. USPS and I imagine some other carriers can be pretty quick / aggressive about repurposing tracking numbers, so just giving a link to their site could leave the customer without info they need to fix a situation.

I used a modal because otherwise I'd be shoe-horning those details into the order summary in ways where they might get cut off, or unclear.

I'll move report an issue to the button bar so it's not in the scrollable area and increase the height. Will also add a link to the summary screen as suggested.

Regarding the bug / lack of update — can you confirm you're still seeing that?

**Comment by mshick** [comment]
@allanlasser If you could take another look at the current version. I also need confirmation as to whether you still see the "scheduled for" bug so I can figure out what might have happened there.

**Comment by allanlasser** [comment]
Yep! Looking now. Sorry, didn't realize you were waiting on that feedback.

**Comment by allanlasser** [comment]
Screen Shot 2022-09-19 at 5 58 46 PM

Yep, still seeing the previously fulfilled order as the "next queued order", although I can see the next queued order exists in recharge: https://deluxe-sample-project-sp.admin.rechargeapps.com/merchant/orders/charges/656182736

**Comment by mshick** [comment]
@allanlasser Ready to test again

**Review by allanlasser — APPROVED** [review]
LGTM!

**Pull request merged**
