### PR TITLE
Handle customers with inactive accounts during sign in / creation / password reset

### PR DESCRIPTION
**Pull request by mshick**
Screenshot 2023-05-03 at 14 05 50

### Test Plan (Steps to test):

1. Attempt to sign in with a known disabled email — `michael+earth1@takeshape.io` works — confirm you get the activation email
1. Same as above for creation
1. Same as above for reset password
2. Now try all three of those with a know active email / account
3. Try resetting the password of an email that doesn't exist
4. Try creating an account that already exists

### CODE REVIEW

**Review by mcat — CHANGES_REQUESTED** [review]
Getting the following error when attempting to reset the password of a known user 

Screenshot 2023-05-03 at 15 51 29

**Comment by mshick** [comment]
@mcat Recaptcha hadn't been set up for that domain. I've updated the settings, and you can now reset passwords.

**Comment by mshick** [comment]
I've added a 5s timeout, after which you are returned to the Sign In page.

**Review by mcat — CHANGES_REQUESTED** [review]
Let's stick with the current UX. Only changes needed are to address the code scanning findings.

**Comment by mshick** [comment]
@mcat Code scans have been addressed.

**Review by asprouse — CHANGES_REQUESTED** [review]

**Review by mcat — APPROVED** [review]

**Review by asprouse — APPROVED** [review]

**Pull request merged**
