### PR TITLE
Strict tsconfig

### PR DESCRIPTION
**Pull request by mshick**
### Test Plan (Steps to test):

1. CI, because this is mostly about the types
1. Regression testing on reviews
1. View a page with reviews IO reviews, like Awesome T-Shirt. Do they look right? Does pagination still work? Can you create a review?
2. Regression test Trustpilot reviews — not sure where those are being displayed. @incompl did you have specific products you set them up on?
3. Broad regression test, including:
4. Go to a product page. 
5. Go to a collection page. 
6. Go to all account pages. 
7. Make account profile edits and save.
8. Do a full add-to-cart and checkout of a regular product and a subscription product.

### CODE REVIEW

**Review by asprouse — CHANGES_REQUESTED** [review]
The rewards page is blank when logged in:
https://penny-git-sc-9761-bugpenny-s-tsconfig-json-str-f63cf7-takeshape.vercel.app/account/rewards

**Comment by mshick** [comment]
@asprouse Looks like our Voucherify acct just lapsed: `{"code":402,"message":"Payment required"}`

**Comment by asprouse** [comment]
> @asprouse Looks like our Voucherify acct just lapsed: `{"code":402,"message":"Payment required"}`

Hmm the page probably should not be blank, but this is the existing behavior. I added a new ticket to capture this:

https://app.shortcut.com/takeshape/story/9915/rewards-page-is-blank

**Review by asprouse — APPROVED** [review]
I have tested all the test steps minus the Trustpilot features and things look good. I filed a few bug tickets by they all happen in `main` so they do not need to be addressed here:
- https://app.shortcut.com/takeshape/story/9915/penny-rewards-page-is-blank
- https://app.shortcut.com/takeshape/story/9916/penny-search-dialog-shows-no-results-found
- https://app.shortcut.com/takeshape/story/9918/penny-saving-marketing-prefs-fails

**Pull request merged**
